development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_DEVELOPMENT_URL'] || 'http://127.0.0.1:8984/rest' %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_TEST_URL'] || 'http://127.0.0.1:8986/rest' %>
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_PROD_URL'] || 'http://127.0.0.1:8983/rest' %>
  base_path: /prod
